name: Update Kaggle Dataset

on:
  schedule:
    - cron: "0 0 * * 0"  # Runs every Sunday at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-dataset:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository with LFS
      uses: actions/checkout@v3
      with:
        lfs: true  # Enables Git Large File Storage

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"

    - name: Install Git LFS
      run: git lfs install

    - name: Install Kaggle CLI
      run: pip install kaggle

    - name: Configure Kaggle API Key
      run: |
        mkdir -p ~/.kaggle
        echo '${{ secrets.KAGGLE_API_KEY }}' > ~/.kaggle/kaggle.json
        chmod 600 ~/.kaggle/kaggle.json

    - name: Download All CSV Files
      run: |
        mkdir -p data  # Ensure data directory exists
        kaggle datasets download -d davidcariboo/player-scores -p data --unzip
        ls -lh data  # Debugging step to verify file sizes

    - name: Track Large CSV Files in LFS
      run: |
        git lfs track "data/game_events.csv"
        git lfs track "data/game_lineups.csv"
        git lfs track "data/appearances.csv"

    - name: Commit and Push Changes
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add .gitattributes
        git add -A
        git commit -m "Updated all dataset files from Kaggle using Git LFS" || echo "No changes to commit"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/ElliottOctave/FootballDashboard.git main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
